### ISSUE TITLE
KeyError: '$EXTMIN'

### ISSUE THREAD

**Issue by gottre** [apendua/dxf2svg#2]
Please help, I got this error

Traceback (most recent call last):
  File "dxf2svg.py", line 134, in <module>
    saveToSVG(svgFile, dxfData)
  File "dxf2svg.py", line 100, in saveToSVG
    minX = dxfData.header['$EXTMIN'][0]
KeyError: '$EXTMIN'

**Comment by apendua** [comment]
@gottre Thank you for reporting.

I believe that this is issue related to the code not being compatible with the latest version of `dxfgrabber`. I am not officially supporting this small project, but I would accept a PR if you would like to create one.
